//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssFontSubset.Avalonia.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssFontSubset.Avalonia.I18n.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HarfBuzz-Subset.
        /// </summary>
        public static string BackendHarfbuzzSubset {
            get {
                return ResourceManager.GetString("BackendHarfbuzzSubset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Harfbuzz-Subset subset fonts..
        /// </summary>
        public static string BackendHarfbuzzSubsetTip {
            get {
                return ResourceManager.GetString("BackendHarfbuzzSubsetTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearInput {
            get {
                return ResourceManager.GetString("ClearInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string DebugOption {
            get {
                return ResourceManager.GetString("DebugOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep subset temp files when enabled..
        /// </summary>
        public static string DebugOptionTip {
            get {
                return ResourceManager.GetString("DebugOptionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ass files. Please check!.
        /// </summary>
        public static string ErrorNoAssFile {
            get {
                return ResourceManager.GetString("ErrorNoAssFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASS Subtitles.
        /// </summary>
        public static string InputAssFiles {
            get {
                return ResourceManager.GetString("InputAssFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Folder.
        /// </summary>
        public static string InputFontFolder {
            get {
                return ResourceManager.GetString("InputFontFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceHan Ellipsis.
        /// </summary>
        public static string SourceHanEllipsis {
            get {
                return ResourceManager.GetString("SourceHanEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A special hack. The ellipses of Source Han fonts will be aligned in the center when enabled..
        /// </summary>
        public static string SourceHanEllipsisTip {
            get {
                return ResourceManager.GetString("SourceHanEllipsisTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subset.
        /// </summary>
        public static string Subset {
            get {
                return ResourceManager.GetString("Subset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subset Completed. Please check Output Folder..
        /// </summary>
        public static string SuccessSubset {
            get {
                return ResourceManager.GetString("SuccessSubset", resourceCulture);
            }
        }
    }
}
